from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from typing import Any

from .common import (
    normalize_tuple,
    require_aware_datetime,
    require_content_hash,
    require_non_empty_tuple,
    require_non_negative,
    require_text,
)


FORBIDDEN_WEIGHT_GENERATORS = {"llm", "raw_llm", "cloud_model", "model_output"}


@dataclass(frozen=True, slots=True)
class SignalBundle:
    signal_bundle_id: str
    ticker: str
    as_of: datetime
    strategic_thesis_score: Decimal
    tactical_technical_score: Decimal
    forward_indicator_score: Decimal
    portfolio_risk_score: Decimal
    formula_versions: dict[str, str]
    input_snapshot_hash: str
    created_at: datetime

    def __post_init__(self) -> None:
        object.__setattr__(self, "signal_bundle_id", require_text(self.signal_bundle_id, "signal_bundle_id"))
        object.__setattr__(self, "ticker", require_text(self.ticker, "ticker").upper())
        object.__setattr__(self, "strategic_thesis_score", Decimal(str(self.strategic_thesis_score)))
        object.__setattr__(self, "tactical_technical_score", Decimal(str(self.tactical_technical_score)))
        object.__setattr__(self, "forward_indicator_score", Decimal(str(self.forward_indicator_score)))
        object.__setattr__(self, "portfolio_risk_score", Decimal(str(self.portfolio_risk_score)))
        if not self.formula_versions:
            raise ValueError("formula_versions must not be empty")
        object.__setattr__(self, "input_snapshot_hash", require_content_hash(self.input_snapshot_hash, "input_snapshot_hash"))
        require_aware_datetime(self.as_of, "as_of")
        require_aware_datetime(self.created_at, "created_at")


@dataclass(frozen=True, slots=True)
class TargetWeights:
    target_weights_id: str
    as_of: datetime
    portfolio_id: str
    cash_weight: Decimal
    weights: dict[str, Decimal]
    constraints: dict[str, Any]
    source_signal_bundle_ids: tuple[str, ...]
    generated_by: str
    validation_status: str
    created_at: datetime

    def __post_init__(self) -> None:
        object.__setattr__(self, "target_weights_id", require_text(self.target_weights_id, "target_weights_id"))
        object.__setattr__(self, "portfolio_id", require_text(self.portfolio_id, "portfolio_id"))
        object.__setattr__(self, "cash_weight", require_non_negative(self.cash_weight, "cash_weight"))
        if not self.weights:
            raise ValueError("weights must not be empty")
        normalized_weights = {require_text(ticker, "weights ticker").upper(): Decimal(str(weight)) for ticker, weight in self.weights.items()}
        object.__setattr__(self, "weights", normalized_weights)
        if not self.constraints:
            raise ValueError("constraints must not be empty")
        object.__setattr__(
            self,
            "source_signal_bundle_ids",
            require_non_empty_tuple(normalize_tuple(self.source_signal_bundle_ids, "source_signal_bundle_ids"), "source_signal_bundle_ids"),
        )
        object.__setattr__(self, "generated_by", require_text(self.generated_by, "generated_by"))
        if self.generated_by.lower() in FORBIDDEN_WEIGHT_GENERATORS:
            raise ValueError("TargetWeights must be generated by deterministic portfolio code")
        object.__setattr__(self, "validation_status", require_text(self.validation_status, "validation_status"))
        if self.validation_status != "validated":
            raise ValueError("TargetWeights require deterministic validation_status='validated'")
        require_aware_datetime(self.as_of, "as_of")
        require_aware_datetime(self.created_at, "created_at")

    @classmethod
    def from_raw_llm_output(cls, raw_output: dict[str, Any]) -> "TargetWeights":
        raise ValueError("TargetWeights cannot be created from raw unvalidated LLM output")


@dataclass(frozen=True, slots=True)
class ImplementationEstimate:
    implementation_estimate_id: str
    ticker_or_portfolio: str
    as_of: datetime
    expected_turnover: Decimal
    spread_cost_bps: Decimal
    slippage_bps: Decimal
    participation_rate: Decimal
    liquidity_limit: Decimal
    implementation_shortfall_bps: Decimal
    created_at: datetime

    def __post_init__(self) -> None:
        object.__setattr__(self, "implementation_estimate_id", require_text(self.implementation_estimate_id, "implementation_estimate_id"))
        object.__setattr__(self, "ticker_or_portfolio", require_text(self.ticker_or_portfolio, "ticker_or_portfolio"))
        object.__setattr__(self, "expected_turnover", require_non_negative(self.expected_turnover, "expected_turnover"))
        object.__setattr__(self, "spread_cost_bps", require_non_negative(self.spread_cost_bps, "spread_cost_bps"))
        object.__setattr__(self, "slippage_bps", require_non_negative(self.slippage_bps, "slippage_bps"))
        object.__setattr__(self, "participation_rate", require_non_negative(self.participation_rate, "participation_rate"))
        object.__setattr__(self, "liquidity_limit", require_non_negative(self.liquidity_limit, "liquidity_limit"))
        object.__setattr__(self, "implementation_shortfall_bps", require_non_negative(self.implementation_shortfall_bps, "implementation_shortfall_bps"))
        require_aware_datetime(self.as_of, "as_of")
        require_aware_datetime(self.created_at, "created_at")
